/*
Script to insert data into CHEMICAL table

100 rows of dummy data
*/


INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (500,'Quis PC','Phosphorus','05/04/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (501,'Aenean LLC','Magnesium','07/22/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (502,'Aliquet Corporation','Nitrogen','08/29/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (503,'Sed Eget Lacus Foundation','Sulfur','03/11/17');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (504,'Arcu Morbi Sit LLC','Calcium','03/02/17');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (505,'Luctus Lobortis Class Foundation','Calcium','04/05/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (506,'Suspendisse Non Leo Foundation','Sulfur','07/05/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (507,'Vitae Company','Copper','09/22/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (508,'Nunc Est Ltd','Calcium','02/14/17');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (509,'Nisi PC','Calcium','01/26/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (510,'Amet Corporation','Iron','10/25/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (511,'Leo Corp.','Potassium','08/11/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (512,'Consequat Purus Maecenas LLP','Nitrogen','05/02/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (513,'In Foundation','Calcium','12/04/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (514,'Suspendisse Non Leo Consulting','Calcium','10/28/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (515,'Eleifend Associates','Zinc','05/21/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (516,'Viverra Donec Tempus Corporation','Potassium','04/24/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (517,'Lorem Auctor LLC','Nitrogen','03/26/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (518,'Vehicula Aliquet Company','Potassium','05/24/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (519,'Non Nisi Institute','Phosphorus','03/23/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (520,'Orci Sem Eget Incorporated','Calcium','08/29/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (521,'Magna Sed Eu LLC','Nitrogen','01/15/17');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (522,'Accumsan Institute','Manganese','07/01/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (523,'Vivamus Nisi Limited','Magnesium','03/08/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (524,'Ridiculus Mus Company','Manganese','02/29/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (525,'Non Dui Nec Institute','Boron','11/19/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (526,'Euismod Associates','Boron','06/18/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (527,'Posuere Enim Nisl Foundation','Phosphorus','03/19/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (528,'Consequat Lectus Sit Limited','Zinc','03/23/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (529,'Fringilla Porttitor LLP','Manganese','04/27/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (530,'Semper PC','Nitrogen','06/30/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (531,'Id Corp.','Boron','08/11/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (532,'Convallis Dolor Inc.','Phosphorus','12/06/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (533,'Suspendisse Foundation','Potassium','01/02/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (534,'Et Libero Proin Associates','Manganese','10/02/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (535,'Tellus LLC','Magnesium','04/27/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (536,'Lacus Quisque Associates','Zinc','04/22/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (537,'Quis Corporation','Boron','08/08/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (538,'Tortor Nunc Foundation','Sulfur','05/06/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (539,'Tellus Aenean Corp.','Zinc','02/25/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (540,'Aliquam Tincidunt Consulting','Boron','02/16/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (541,'Cum Sociis Natoque Corporation','Sulfur','07/10/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (542,'Pede Consulting','Iron','04/10/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (543,'Orci Industries','Copper','11/06/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (544,'Praesent Luctus Company','Boron','01/27/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (545,'Erat Corp.','Copper','11/25/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (546,'Mauris Eu Corp.','Nitrogen','02/14/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (547,'Mollis Lectus Industries','Sulfur','11/24/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (548,'Sed PC','Copper','07/27/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (549,'Eget Associates','Sulfur','10/03/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (550,'Vestibulum Ante Company','Calcium','05/12/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (551,'Nec Industries','Sulfur','11/25/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (552,'Integer Associates','Magnesium','01/18/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (553,'Tempus Eu Ligula Corporation','Zinc','09/27/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (554,'Ipsum Dolor LLC','Zinc','10/11/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (555,'Tellus Limited','Iron','07/06/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (556,'Condimentum Donec At LLC','Copper','11/06/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (557,'Ligula Nullam Associates','Manganese','05/17/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (558,'Elit Pretium Et PC','Manganese','10/02/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (559,'Velit Foundation','Phosphorus','11/21/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (560,'Curabitur Sed Tortor LLP','Copper','05/10/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (561,'Nec Orci Corp.','Boron','07/18/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (562,'Eu Augue Industries','Iron','03/12/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (563,'Nunc In Corporation','Manganese','03/11/17');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (564,'Rutrum Fusce Dolor Incorporated','Magnesium','12/19/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (565,'Varius Orci In Limited','Iron','05/15/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (566,'Nibh Enim Gravida Industries','Zinc','09/30/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (567,'Ligula Aenean Consulting','Potassium','12/29/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (568,'Euismod Consulting','Boron','10/03/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (569,'Non Magna Nam Corporation','Boron','01/19/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (570,'Facilisis Suspendisse Inc.','Nitrogen','06/28/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (571,'Arcu Curabitur Ut LLP','Phosphorus','02/20/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (572,'Non Justo Proin Foundation','Magnesium','07/03/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (573,'Nullam Limited','Iron','07/18/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (574,'Bibendum Incorporated','Boron','02/14/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (575,'Molestie Dapibus Ligula Inc.','Magnesium','07/08/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (576,'Eu Tellus Foundation','Magnesium','10/02/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (577,'Sem Vitae Consulting','Zinc','10/18/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (578,'Sociis Natoque Penatibus LLP','Magnesium','06/25/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (579,'Vitae Sodales Nisi LLC','Potassium','07/04/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (580,'Ultricies LLP','Iron','02/20/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (581,'Nullam Incorporated','Nitrogen','04/02/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (582,'Quis Ltd','Iron','01/19/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (583,'Ac Risus Ltd','Copper','01/20/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (584,'Nunc Associates','Potassium','01/31/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (585,'Vestibulum Accumsan Company','Zinc','08/08/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (586,'Leo Corp.','Manganese','04/08/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (587,'Suspendisse Dui Institute','Zinc','03/28/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (588,'Ac Institute','Boron','06/13/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (589,'Elementum Dui Quis Inc.','Iron','09/20/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (590,'Massa Inc.','Zinc','08/18/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (591,'Elit Curabitur Company','Magnesium','11/06/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (592,'Libero Donec Consectetuer PC','Zinc','04/08/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (593,'Sed Dictum Eleifend Limited','Phosphorus','09/10/15');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (594,'Dui Cum Limited','Boron','05/08/14');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (595,'Morbi Accumsan Ltd','Nitrogen','10/05/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (596,'Tincidunt Incorporated','Potassium','01/07/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (597,'Tellus Company','Copper','07/07/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (598,'Lacus Ltd','Copper','06/05/16');
INSERT INTO CHEMICAL (MANUFACTURER_PRODUCT_CODE,MANUFACTURER,NAME,DATE_APPLIED) VALUES (599,'Urna Justo Faucibus PC','Copper','12/08/14');




/*
Make sure 100 rows are inserted.
*/
SELECT COUNT(*) FROM CHEMICAL;
