/*
Script to insert data into CUSTOMER_ADDRESS table

100 rows of dummy data
*/

INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (300,'P.O. Box 277, 6741 Fermentum St.','Cholet','PA',65977);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (301,'9003 Et Avenue','Ankara','Ankara',37503);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (302,'1388 Nulla. Ave','Columbus','Ohio',48139);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (303,'P.O. Box 736, 1256 Donec St.','Norrkˆping','÷stergˆtlands l‰n',62406);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (304,'Ap #721-9072 Vestibulum Rd.','Reus','Catalunya',11911);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (305,'434-9360 Vestibulum. Av.','Tobermory','AR',32647);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (306,'744-1289 Duis Rd.','Mostazal','VI',17027);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (307,'400 Ornare Av.','Retie','AN',70613);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (308,'531-9447 Sed Ave','Viransehir','Sanliurfa',79882);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (309,'Ap #275-6972 Lacus. Avenue','Santa Marina','CAM',36871);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (310,'132-1963 Nunc Rd.','Augusta','GA',66403);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (311,'397-4439 A, Road','Ostrowiec Swietokrzyski','Swietokrzyskie',12348);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (312,'P.O. Box 541, 1859 Quam Road','≈kersberga','Stockholms l‰n',61994);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (313,'P.O. Box 728, 1837 Egestas St.','Lo Prado','Metropolitana de Santiago',74115);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (314,'371-1716 Mauris Road','Plock','Mazowieckie',25367);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (315,'8664 Ultricies Road','Marseille','Provence-Alpes-CÙte d''Azur',73584);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (316,'4145 Et, Rd.','Paranagu·','PR',57751);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (317,'3209 Nec St.','Kano','Kano',29896);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (318,'898-5773 Dolor Avenue','Vichte','WV',98122);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (319,'4441 Semper Avenue','Whyalla','SA',95815);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (320,'3168 Lacus, Ave','Lowell','Massachusetts',49942);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (321,'663 Aliquam Ave','Avesta','Dalarnas l‰n',65183);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (322,'349-2852 Morbi Ave','Elsene','Brussels Hoofdstedelijk Gewest',88098);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (323,'2021 Luctus Av.','Rodez','MI',95947);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (324,'Ap #802-9774 Erat Av.','Darica','Koc',83012);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (325,'204 Sit Av.','Isle-aux-Coudres','Quebec',54975);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (326,'953-6457 Adipiscing. Road','Lithgow','New South Wales',98114);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (327,'9399 Odio. Street','Damoh','MP',96876);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (328,'Ap #415-9788 Lacinia Road','Cork','M',52574);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (329,'Ap #423-1377 Auctor, St.','Vˆlklingen','Schleswig-Holstein',18476);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (330,'P.O. Box 975, 6622 Ac Av.','Casper','WY',54991);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (331,'467-6438 Tincidunt Road','Vienna','Wie',91927);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (332,'5725 Nulla. Rd.','Melipeuco','IX',32858);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (333,'1249 Fusce Av.','Camaragibe','Pernambuco',55684);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (334,'P.O. Box 934, 6811 Lectus. Avenue','Legnica','Dolnoslaskie',78291);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (335,'5562 Non Rd.','Mount Isa','QLD',24078);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (336,'P.O. Box 278, 2372 Dolor. Rd.','Huissen','Gelderland',25707);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (337,'Ap #545-247 Montes, Road','Bekkerzeel','VB',19027);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (338,'283-6915 Consequat Av.','TorrejÛn de Ardoz','MA',12278);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (339,'8574 Sem Rd.','Cork','Munster',53162);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (340,'292-7327 Vitae St.','Nelson','SI',52922);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (341,'2517 Sociis St.','Sluis','Zeeland',29153);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (342,'465-1861 Enim, St.','Tamworth','New South Wales',58207);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (343,'Ap #345-4690 Faucibus Rd.','Valenciennes','Nord-Pas-de-Calais',87961);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (344,'P.O. Box 868, 4017 Erat. Av.','Gulfport','Mississippi',85768);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (345,'P.O. Box 120, 754 Eu Ave','Vˆcklabruck','Upper Austria',77164);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (346,'395-4303 Aenean Rd.','Vienna','Vienna',57208);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (347,'Ap #181-8715 Iaculis St.','Hawera','NI',59794);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (348,'1275 Sed, St.','Paignton','DE',90691);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (349,'427-8489 Cursus Street','Dibrugarh','Assam',20113);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (350,'3342 Etiam Street','Southampton','Hampshire',23632);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (351,'Ap #204-236 Nascetur Avenue','Castel di Tora','LAZ',33362);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (352,'Ap #401-3653 Libero. Avenue','Gespeg','QC',42369);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (353,'390-4667 Ut, Av.','San Felipe','SJ',81435);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (354,'648-2926 Nec, Av.','Istanbul','Ist',60463);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (355,'Ap #964-873 Iaculis, St.','LÛdz','lÛdzkie',46451);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (356,'Ap #445-8457 Lorem St.','San Juan (San Juan de Tib·s)','SJ',49036);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (357,'P.O. Box 221, 6427 Ut, St.','Vienna','Wie',14421);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (358,'911-2641 Molestie Rd.','Gliwice','Slaskie',64164);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (359,'P.O. Box 729, 510 Eros Road','Kansas City','Kansas',89019);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (360,'2883 Interdum. Street','Iqaluit','NU',74472);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (361,'944-5704 Dui. Avenue','Millet','AB',31786);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (362,'Ap #550-4239 Ut Road','Lourdes','Manitoba',18444);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (363,'397-6679 Dui Av.','Serik','Ant',82005);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (364,'580-8296 Sem St.','White Rock','BC',60336);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (365,'P.O. Box 785, 2892 Proin Street','Collines-de-l''Outaouais','QC',42263);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (366,'9992 Magnis St.','Leeds','YK',49215);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (367,'P.O. Box 527, 4994 Et, Avenue','Port Hope','Ontario',50839);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (368,'P.O. Box 830, 7994 Justo Rd.','Frignano','CAM',37339);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (369,'124-5665 Nulla Av.','Auckland','NI',62808);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (370,'904-7041 Lectus Street','Motueka','SI',25394);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (371,'P.O. Box 513, 2304 Eu St.','Cork','Munster',64995);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (372,'6920 Tristique Street','Dunbar','East Lothian',49267);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (373,'Ap #948-2800 Maecenas Street','Elx','Comunitat Valenciana',97063);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (374,'2187 Donec Av.','Istanbul','Istanbul',70824);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (375,'240 Vel, Ave','Morrinsville','North Island',48171);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (376,'4327 Mauris Street','Istanbul','Ist',29494);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (377,'725-9678 Vestibulum Street','Vandoeuvre-lËs-Nancy','LO',80872);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (378,'889-8860 Ac Avenue','New Westminster','BC',61554);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (379,'577-1311 Phasellus Street','Laramie','WY',18415);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (380,'P.O. Box 577, 1448 Et St.','Worcester','Massachusetts',12627);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (381,'589-3158 Magna. St.','Fontaine-l''Evêque','HE',89465);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (382,'Ap #435-4044 Non St.','Zamosc','LU',23730);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (383,'Ap #626-2163 Eu St.','Ramsdonk','VB',39400);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (384,'365-7997 Aliquam Rd.','Lancaster','LA',28268);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (385,'7206 Donec Road','Campbelltown','New South Wales',11141);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (386,'Ap #230-8437 Mi Avenue','Poviglio','Emilia-Romagna',85703);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (387,'877-835 Sed Ave','Swan Hill','Victoria',73646);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (388,'896-5543 Tristique St.','Nelson','South Island',74227);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (389,'P.O. Box 311, 5297 Dui. Rd.','Wilmington','DE',50810);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (390,'P.O. Box 877, 8289 Tempus St.','Osasco','SP',45343);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (391,'4713 Id, Rd.','Mielec','Podkarpackie',61112);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (392,'908-8765 Dignissim. Road','Quinte West','ON',15972);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (393,'143-7484 Rutrum, Rd.','Bauchi','Bauchi',11034);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (394,'112-1821 Ornare, Rd.','Lithgow','New South Wales',17402);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (395,'P.O. Box 663, 320 Ac St.','Okigwe','IM',49856);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (396,'P.O. Box 614, 1317 A Rd.','Katihar','BR',49156);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (397,'5623 Consectetuer Av.','Galway','C',87559);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (398,'7049 Ante Rd.','GijÛn','Principado de Asturias',43171);
INSERT INTO CUSTOMER_ADDRESS (CUSTOMER_ID,STREET,CITY,STATE_CODE,ZIP_CODE) VALUES (399,'Ap #128-935 Eleifend Road','San Juan de Dios','SJ',13551);


/*
Validation
*/
SELECT COUNT(*) FROM CUSTOMER_ADDRESS;