
/*
Script to insert data into CUSTOMER table

100 rows of dummy data
*/
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (300,'Colorado','Kelsey');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (301,'Peter','Lester');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (302,'Daryl','Robin');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (303,'Harper','Carlos');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (304,'Rinah','Thomas');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (305,'Aidan','Cheryl');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (306,'Phelan','Pearl');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (307,'Yael','Shad');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (308,'Austin','Dane');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (309,'Solomon','Ora');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (310,'Berk','Jared');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (311,'Kibo','Aristotle');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (312,'Quinn','Larissa');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (313,'Zeus','Armand');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (314,'Joelle','Alma');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (315,'Lane','Karyn');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (316,'Jonas','Kevyn');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (317,'Caleb','Merrill');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (318,'Unity','Olympia');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (319,'Bo','Emi');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (320,'Rinah','Harlan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (321,'Tyler','Desiree');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (322,'Blaze','May');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (323,'Shannon','Jarrod');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (324,'Dara','Hop');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (325,'Rachel','Rinah');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (326,'Louis','Ivana');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (327,'Neville','Uriel');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (328,'Peter','Priscilla');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (329,'Nathaniel','Levi');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (330,'Phelan','Acton');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (331,'Echo','Alexander');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (332,'Kylie','Solomon');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (333,'April','Nathaniel');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (334,'Gwendolyn','Candace');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (335,'Ariana','Brandon');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (336,'Jarrod','Kalia');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (337,'Wendy','Cathleen');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (338,'Zephr','Mohammad');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (339,'Fleur','Sierra');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (340,'Odysseus','Dylan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (341,'Hannah','Allen');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (342,'Allistair','Adam');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (343,'Dustin','Heather');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (344,'Jada','Cairo');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (345,'Rhonda','Kaden');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (346,'Inez','Tad');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (347,'Raphael','Skyler');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (348,'Rachel','Maisie');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (349,'Venus','Breanna');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (350,'Adria','Rajah');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (351,'Baker','Brenden');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (352,'Allegra','Avram');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (353,'Donovan','Hop');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (354,'Yvonne','Kiona');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (355,'Colleen','Myra');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (356,'Heather','Bradley');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (357,'Maxwell','Nelle');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (358,'Luke','Galena');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (359,'Cassady','Jordan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (360,'Drake','Megan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (361,'Cynthia','Wesley');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (362,'Whoopi','Sara');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (363,'Imelda','Kylee');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (364,'Simon','Leila');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (365,'Regina','Hilel');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (366,'Luke','Chadwick');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (367,'Yardley','Vladimir');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (368,'Vincent','Serena');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (369,'Maya','Richard');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (370,'Bevis','Herman');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (371,'Harper','Melvin');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (372,'Raphael','Nomlanga');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (373,'Alexandra','Giacomo');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (374,'Buffy','Leigh');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (375,'Benjamin','Drake');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (376,'Reece','Baxter');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (377,'Perry','Mia');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (378,'Alexis','Athena');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (379,'Stephanie','Elizabeth');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (380,'Freya','Prescott');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (381,'Oprah','Caleb');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (382,'Aurelia','Mallory');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (383,'Sacha','Mikayla');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (384,'Piper','Herrod');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (385,'Grady','Gail');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (386,'Latifah','Mona');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (387,'Philip','Madison');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (388,'Bree','Orla');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (389,'Lars','Kaden');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (390,'Robert','Tobias');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (391,'Barry','Brody');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (392,'Xander','Dane');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (393,'Erich','Evan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (394,'Chase','Teagan');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (395,'Callie','Paloma');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (396,'Jared','Remedios');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (397,'Signe','Caesar');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (398,'Kylie','Rose');
INSERT INTO CUSTOMER (CUSTOMER_ID,FIRST_NAME,LAST_NAME) VALUES (399,'Carla','Indigo');


/* 
Check for number of rows inserted
Should be 100
*/

SELECT COUNT(*) FROM CUSTOMER;