/*
Script to remove uniqueness to 1-M, M-1, M-M relations
Author : Srinivas
*/

UPDATE FIELD SET FIELD.FARMER_ID = 103 WHERE FIELD.FARMER_ID BETWEEN 100 AND 109;  
UPDATE FIELD SET FIELD.FARMER_ID = 117 WHERE FIELD.FARMER_ID BETWEEN 110 AND 119;
UPDATE FIELD SET FIELD.FARMER_ID = 147 WHERE FIELD.FARMER_ID BETWEEN 140 AND 149;
UPDATE FIELD SET FIELD.FARMER_ID = 194 WHERE FIELD.FARMER_ID BETWEEN 190 AND 199;



UPDATE ORDER_DETAILS SET ORDER_DETAILS.CUSTOMER_ID = 302 WHERE ORDER_DETAILS.CUSTOMER_ID BETWEEN 300 AND 309;  
UPDATE ORDER_DETAILS SET ORDER_DETAILS.CUSTOMER_ID = 317 WHERE ORDER_DETAILS.CUSTOMER_ID BETWEEN 310 AND 319;
UPDATE ORDER_DETAILS SET ORDER_DETAILS.CUSTOMER_ID = 347 WHERE ORDER_DETAILS.CUSTOMER_ID BETWEEN 340 AND 349;
UPDATE ORDER_DETAILS SET ORDER_DETAILS.CUSTOMER_ID = 394 WHERE ORDER_DETAILS.CUSTOMER_ID BETWEEN 390 AND 399;