/*
Script to insert data into USES table

100 rows of dummy data
*/

INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (600,500);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (601,501);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (602,502);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (603,503);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (604,504);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (605,505);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (606,506);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (607,507);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (608,508);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (609,509);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (610,510);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (611,511);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (612,512);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (613,513);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (614,514);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (615,515);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (616,516);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (617,517);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (618,518);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (619,519);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (620,520);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (621,521);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (622,522);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (623,523);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (624,524);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (625,525);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (626,526);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (627,527);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (628,528);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (629,529);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (630,530);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (631,531);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (632,532);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (633,533);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (634,534);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (635,535);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (636,536);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (637,537);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (638,538);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (639,539);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (640,540);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (641,541);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (642,542);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (643,543);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (644,544);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (645,545);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (646,546);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (647,547);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (648,548);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (649,549);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (650,550);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (651,551);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (652,552);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (653,553);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (654,554);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (655,555);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (656,556);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (657,557);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (658,558);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (659,559);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (660,560);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (661,561);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (662,562);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (663,563);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (664,564);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (665,565);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (666,566);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (667,567);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (668,568);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (669,569);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (670,570);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (671,571);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (672,572);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (673,573);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (674,574);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (675,575);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (676,576);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (677,577);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (678,578);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (679,579);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (680,580);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (681,581);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (682,582);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (683,583);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (684,584);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (685,585);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (686,586);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (687,587);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (688,588);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (689,589);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (690,590);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (691,591);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (692,592);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (693,593);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (694,594);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (695,595);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (696,596);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (697,597);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (698,598);
INSERT INTO USES (FIELD_ID,MANUFACTURER_PRODUCT_CODE) VALUES (699,599);



/*
Validation
*/

SELECT COUNT(*) FROM USES;